name: SPM TEST
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Test Deploy"
        env:
          GH_TOKEN: ${{secrets.MY_TOKEN}}
          PUBLISH_DIR: "./main"
